services:
    lemon_rest_demo.event.search_sanitizer_subscriber:
        class: Lemon\RestDemoBundle\Event\SearchSanitizerSubscriber
        tags:
            - { name: lemon_rest.event_subscriber }

    monolog_line_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments: [null, null, true, false]
